option("static", {default = false, description = "Compile Static Libraries"})

set_policy("check.auto_ignore_flags", true)

set_languages("c23", "c++20")
set_optimize("fastest")

set_installdir("$(projectdir)/$(builddir)")

add_cxflags(
    "-Wold-style-cast" -- gcc / clang
)

if is_mode("debug") then
    add_cxflags(
        "-g3", "-ggdb3", -- gcc / clang
        "-Zi", "-FS" -- msvc
    )
    add_ldflags(
        "-DEBUG" -- msvc
    )
end

if has_config("static") then
    add_cxflags(
        "-MT" -- msvc
    )
end

add_requireconfs("*", {configs = {shared = not has_config("static")}})

add_requires("libsdl3")
if is_plat("windows") then
    add_requires("libsdl3_ttf")
else
    add_requires("brew::sdl3_ttf", {alias = "libsdl3_ttf"})
end
add_requires("libsdl3_image")
add_requires("fmt")
add_requires("nlohmann_json")
add_requires("cpr")
add_requires("glaze")

target("discord-presence")
    if has_config("static") then
        set_kind("static")
    else
        set_kind("shared")
        add_rules("utils.symbols.export_all", {export_classes = true})
    end
    after_load(function ()
        os.exec("git submodule update --init --recursive")
    end)
    add_files("discord-presence/src/*.cpp")
    if is_plat("windows") then
        add_files("discord-presence/src/platform/windows.cpp")
    end
    add_includedirs("discord-presence/include")
    add_packages("glaze", "fmt")
    set_languages("c23", "c++23")

target("lore-game")
    set_kind("binary")
    add_files("src/**.cpp")
    add_includedirs("discord-presence/include", "include")
    add_packages("libsdl3", "libsdl3_ttf", "libsdl3_image", "fmt", "nlohmann_json", "cpr")
    add_deps("discord-presence")
    on_load(function ()
        local config = io.open("$(projectdir)/config.json", "r")
        local configHeader = io.open("$(projectdir)/include/engine/config.hpp", "w")
        configHeader:write("// Autogenerated from config.json\n#pragma once\n#include <nlohmann/json.hpp>\ninline const nlohmann::json config = nlohmann::json::parse(R\"(" .. config:read("*all") .. ")\");")
    end)
    after_install(function (target)        
        os.cp("$(projectdir)/resources/", "$(projectdir)/$(builddir)/bin")
    end)
    set_languages("c23", "c++23")