option("static", {default = false, description = "Compile Static Libraries"})

set_languages("c23", "c++20")
set_optimize("fastest")
set_warnings("more")

local runtimes = {}

if is_mode("debug") then
    set_symbols("debug")
    if has_config("static") then
        table.insert(runtimes, "MTd")
    else
        table.insert(runtimes, "MDd")
    end
else
    if has_config("static") then
        table.insert(runtimes, "MT")
    else
        table.insert(runtimes, "MD")
    end
end

if has_config("static") then
    table.insert(runtimes, "c++_static")
    table.insert(runtimes, "stdc++_static")
else
    table.insert(runtimes, "c++_shared")
    table.insert(runtimes, "stdc++_shared")
end

set_runtimes(table.unpack(runtimes))

set_installdir("$(projectdir)/$(builddir)")

add_requireconfs("*", {configs = {
    shared = not has_config("static"),
    vs_runtime = runtimes[1],
    debug = is_mode("debug"),
    public = true
}})

if not is_plat("windows") then
    package("freetype")
        add_links("z", "png", "stdc++", "bz2")
    package_end()
end

add_requires("libsdl3")
add_requires("libsdl3_ttf")
add_requires("libsdl3_image")
add_requires("fmt")
add_requires("nlohmann_json")
add_requires("cpr")
add_requires("glaze")

target("discord-presence")
    set_kind(has_config("static") and "static" or "shared")
    after_load(function ()
        os.exec("git submodule update --init --recursive")
    end)
    if not has_config("static") then
        add_rules("utils.symbols.export_all", {export_classes = true})
    end
    add_files("discord-presence/src/*.cpp")
    if is_plat("windows") then
        add_files("discord-presence/src/platform/windows.cpp")
    end
    add_includedirs("discord-presence/include")
    add_packages("glaze", "fmt")
    set_languages("c23", "c++23")

target("lore-game")
    set_kind("binary")
    add_files("src/**.cpp")
    add_includedirs("discord-presence/include", "include")
    add_packages("libsdl3", "libsdl3_ttf", "libsdl3_image", "fmt", "nlohmann_json", "cpr")
    add_deps("discord-presence")
    on_load(function ()
        local config = io.open("$(projectdir)/config.json", "r")
        local configHeader = io.open("$(projectdir)/include/engine/config.hpp", "w")
        configHeader:write("// Autogenerated from config.json\n#pragma once\n#include <nlohmann/json.hpp>\ninline const nlohmann::json config = nlohmann::json::parse(R\"(" .. config:read("*all") .. ")\");")
    end)
    after_install(function (target)        
        os.cp("$(projectdir)/resources/", "$(projectdir)/$(builddir)/bin")
    end)
    set_languages("c23", "c++23")