name: Build

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        libs: [shared, static]
        config:
        - name: Windows
          os: windows-latest
          id: windows

        - name: Linux
          os: ubuntu-latest
          id: linux

        - name: macOS
          os: macos-latest
          id: macosx

    name: ${{ matrix.config.name }} (${{ matrix.libs }})
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upgrade CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: ${{ matrix.config.name }}-${{ matrix.libs }}
          build-cache: true
          build-cache-key: ${{ matrix.config.name }}-${{ matrix.libs }}
          package-cache: true
          package-cache-key: ${{ matrix.config.name }}-${{ matrix.libs }}

      - name: Set up Homebrew
        if: matrix.config.id != 'windows'
        uses: Homebrew/actions/setup-homebrew@main
      
      - name: Install GCC
        if: matrix.config.id != 'windows'
        run: brew install gcc

      - name: Config
        run: >
          xmake config
          -p ${{ matrix.config.id }}
          -m release
          --static=${{ matrix.libs == 'static' && 'y' || 'n' }}
          ${{ matrix.config.id != 'windows' && '--toolchain=gcc' || '' }}
          --policies=build.ccache:y
          -vy
      
      - name: Build
        run: xmake -vy
      
      - name: Install
        run: xmake install -vy

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.config.id }}-${{ matrix.libs }}
          path: build/bin
