name: Build

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          id: win

        - name: Linux
          os: ubuntu-latest
          id: linux

        - name: macOS
          os: macos-latest
          id: mac

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup CPM Cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/cpm-cache
          key: cpm-${{ matrix.config.id }}-v1-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            cpm-${{ matrix.config.id }}-v1-

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install X11
        if: ${{ matrix.config.id == 'linux' }}
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install xorg openbox -y
      
      - name: Run CMake and Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=RelWithDebugInfo -B build -G Ninja
          ninja -C build

      - name: Print Build for Debugging
        shell: bash
        run: ls -la build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.config.id }}
          path: |
            build/*.exe
            build/*.pdb
