name: Build

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        libs: [shared, static]
        config:
        - name: Windows
          os: windows-latest
          id: windows

        - name: Linux
          os: ubuntu-latest
          id: linux

        # macOS is broken with SDL3_image :(
        # - name: macOS
        #   os: macos-latest
        #   id: macosx

    name: ${{ matrix.config.name }} (${{ matrix.libs }})
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update Packages
        if: matrix.config.id == 'linux'
        run: sudo apt update

      - name: Install Packages
        if: matrix.config.id == 'linux'
        run: >
          sudo apt install
          libudev-dev
          libdbus-1-dev
          libpipewire-0.3-dev
          libwayland-dev
          libwayland-bin
          libxkbcommon-dev
          libegl-dev
          libgl-dev
        
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          disable_annotations: true

      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MSYS2
        if: matrix.config.id == 'windows'
        uses: msys2/setup-msys2@v2
      
      - name: Set up GCC
        if: matrix.config.id != 'windows'
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 12

      - name: Install Python Dependencies
        run: python -m pip install meson ninja
      
      - name: Setup
        run: >
          meson setup
          build
          --default-library ${{ matrix.libs }}
          --optimization 3
          --buildtype release
      
      - name: Build
        run: >
          meson compile
          -C build
          -j 0
      
      - name: Copy Binaries
        shell: bash
        run: |
          set +e
          mkdir build/bin
          cp -r build/$(meson introspect build --projectinfo -i | jq -r '.descriptive_name'){,.exe} build/bin
          cp -r build/*.{dll,so,dylib} build/bin
          cp -r build/subprojects/*/*.{dll,so,dylib} build/bin
          cp -r build/subprojects/*/*/*.{dll,so,dylib} build/bin
          cp -r resources build/bin
          set -e

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.config.id }}-${{ matrix.libs }}
          path: build/bin
